Repository testomatio/reporter, pull requests merged in 2023-11, with the labels that each got.

#250 [ISSUE-232] check -c before opts using
  lib/bin/startTest.js
Labels: bug

#237 add support of .env file
  docs/env-variables.md
  lib/adapter/cypress-plugin/index.js
  lib/config.js
  lib/pipe/gitlab.js
  lib/pipe/testomatio.js
  lib/storages/logger.js
  lib/xmlReader.js
  types.d.ts
Labels: in progress

#221 Html pipe
  docs/pipes/html.md
  docs/pipes/images/html-pipe.png
  lib/constants.js
  lib/pipe/html.js
  lib/pipe/index.js
  lib/template/template-draft.hbs
  lib/template/testomatio.hbs
  package.json
  tests/pipes/csv_pipe_test.js
  tests/pipes/html_pipe_test.js
Labels: enhancement

#258 [TASK-257] Push screenshots to Cypress artifacts
  lib/adapter/cypress-plugin/index.js
Labels: bug, cypress, priority high, artifacts
